Online_Education/Online_Education/Areas/Admin/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Online_Education.Areas.Admin.Models;
namespace Online_Education.Areas.Admin.Controllers
{
    [Authorize]
    public class InfoController : Controller
    {
        OnlineEducationEntities db = new OnlineEducationEntities();
        // GET: Admin/Info
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            TaiKhoan tk = (TaiKhoan)Session["TaiKhoan"];
            int idtk = tk.ID;
            int? idcv = tk.IDChucVu;
            if (idcv == 1)
            {
                return null;
            }
            // Verify
            GiangVien gv = db.GiangViens.SingleOrDefault(z => z.IDTaiKhoan == idtk);
            if (gv != null)
            {
                ViewBag.GiangVien = gv;
            }
            return View(gv);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaThongTin(FormCollection fc,HttpPostedFileBase file)
        {
            int idtk = int.Parse(fc["idtk"]);
            GiangVien gv = db.GiangViens.SingleOrDefault(z => z.IDTaiKhoan == idtk);
            if (file != null)
            {
                gv.Anh = file.FileName;
                var path = Path.Combine(Server.MapPath("../../HinhAnh"), file.FileName);
                file.SaveAs(path);
            }
            if (gv != null)
            {
                gv.HoTen_GV = fc["hotengv"];
                gv.NgaySinh = fc["ngaysinh"];
                gv.SDT = fc["sdt"];
                gv.Email = fc["email"];
                gv.DiaChi = fc["diachi"];
                gv.MoTa = fc["mota1"];

                db.SaveChanges();
            }
            return RedirectToAction("Index");

        }
    }
}

Online_Education/Online_Education/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    @Styles.Render("~/Content/css")
    <style>
        * {
            font-family: Arial;
        }
    </style>
</head>

<body class="skin-2">
    @RenderPage("_navbar.cshtml")

    <div class="main-container ace-save-state" id="main-container">
        <script type="text/javascript">
            try { ace.settings.loadState('main-container') } catch (e) { }
        </script>

        @RenderPage("_Sidebar.cshtml")

        <div class="main-content">
            <div class="main-content-inner">
                <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="ace-icon fa fa-home home-icon"></i>
                            <a href="#">Trang chủ</a>
                        </li>
                        <li class="active">@ViewBag.Title</li>
                    </ul><!-- /.breadcrumb -->

                    <div class="nav-search" id="nav-search">
                        <form class="form-search">
                            <span class="input-icon">
                                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                                <i class="ace-icon fa fa-search nav-search-icon"></i>
                            </span>
                        </form>
                    </div><!-- /.nav-search -->
                </div>

                <div class="page-content">

                    <div class="row">
                        <div class="col-xs-12">
                            <!-- PAGE CONTENT BEGINS -->
                            @RenderBody()
                            <!-- PAGE CONTENT ENDS -->
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.page-content -->
            </div>
        </div><!-- /.main-content -->



        <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
            <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
        </a>
    </div>
    @Scripts.Render("~/Content/scripts")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            var title = $('#title').text();
            var listLi = document.querySelectorAll('.nav-list li');
            listLi.forEach(function (ele) {
                ele.classList.remove('active');
            });
            $("#" + title).addClass("active");
            Load();
        });
    </script>
</body>
</html>

Online_Education/Online_Education/Areas/Admin/Views/Shared/_Sidebar.cshtml
<div id="sidebar" class="sidebar responsive ace-save-state">
    <script type="text/javascript">
        try { ace.settings.loadState('sidebar') } catch (e) { }
    </script>


    <ul class="nav nav-list">
        <li class="" id="tintuc">
            <a href="@Url.Content("~/Admin/TinTuc/Index")">
                <i class="menu-icon fa fa-newspaper-o"></i>
                <span class="menu-text">Tin tức</span>
            </a>
            <b class="arrow"></b>
        </li>
        @if (Session["IDChucVu"].ToString() == "1")
        {
            <li class="active" id="loaikhoahoc">
                <a href="@Url.Content("~/Admin/Home/Index")">
                    <i class="menu-icon fa fa-list"></i>
                    <span class="menu-text"> Loại khóa học</span>
                </a>
                <b class="arrow"></b>
            </li>
        }
        <li class="" id="khoahoc">
            <a href="@Url.Content("~/Admin/KhoaHoc/Index")">
                <i class="menu-icon fa fa-list-alt"></i>
                <span class="menu-text"> Khóa học</span>
            </a>
            <b class="arrow"></b>
        </li>
        <li class="" id="hocvien">
            <a href="@Url.Content("~/Admin/HocVien/Index")">
                <i class="menu-icon fa fa-users"></i>
                <span class="menu-text">Học viên</span>
            </a>
            <b class="arrow"></b>
        </li>
        @if (Session["IDChucVu"].ToString() == "1")
        {
            <li class="" id="giangvien">
                <a href="@Url.Content("~/Admin/GiangVien/Index")">
                    <i class="menu-icon fa fa-user-secret"></i>
                    <span class="menu-text">Giảng viên</span>
                </a>
                <b class="arrow"></b>
            </li>
        }
        @if (Session["IDChucVu"].ToString() == "1")
        {
            <li class="" id="taikhoan">
                <a href="@Url.Content("~/Admin/TaiKhoan/Index")">
                    <i class="menu-icon fa fa-user"></i>
                    <span class="menu-text">Tài khoản</span>
                </a>
                <b class="arrow"></b>
            </li>
        }
        <li class="" id="gopy">
            <a href="@Url.Content("~/Admin/GopY/Index")">
                <i class="menu-icon fa fa-envelope"></i>
                <span class="menu-text"> Góp ý</span>
            </a>
            <b class="arrow"></b>
        </li>
        <li class="" id="lich">
            <a href="calendar.html">
                <i class="menu-icon fa fa-calendar"></i>

                <span class="menu-text">
                    Lịch học

                    <span class="badge badge-transparent tooltip-error" title="2 Important Events">
                        <i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
                    </span>
                </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="" id="anh">
            <a href="gallery.html">
                <i class="menu-icon fa fa-picture-o"></i>
                <span class="menu-text"> Thư viện  </span>
            </a>

            <b class="arrow"></b>
        </li>


    </ul><!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>
</div>

Online_Education/Online_Education/Areas/Admin/Views/Shared/_footer.cshtml
<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
            <span class="bigger-120">
                <span class="blue bolder">Ace</span>
                Application &copy; 2013-2014
            </span>

            &nbsp; &nbsp;
            <span class="action-buttons">
                <a href="#">
                    <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
                </a>
            </span>
        </div>
    </div>
</div>

Online_Education/Online_Education/Areas/Admin/Views/Shared/_navbar.cshtml
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
            <a href="index.html" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    Group 8 Center
                </small>
            </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">

                <li class="green dropdown-modal">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
                        <span class="badge badge-success">5</span>
                    </a>

                    <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="ace-icon fa fa-envelope-o"></i>
                            5 Messages
                        </li>

                        <li class="dropdown-content">
                            <ul class="dropdown-menu dropdown-navbar">
                                <li>
                                    <a href="#" class="clearfix">
                                        <img src="~/Content/Back_End/assets/images/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                                        <span class="msg-body">
                                            <span class="msg-title">
                                                <span class="blue">Alex:</span>
                                                Ciao sociis natoque penatibus et auctor ...
                                            </span>

                                            <span class="msg-time">
                                                <i class="ace-icon fa fa-clock-o"></i>
                                                <span>a moment ago</span>
                                            </span>
                                        </span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="clearfix">
                                        <img src="~/Content/Back_End/assets/images/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                                        <span class="msg-body">
                                            <span class="msg-title">
                                                <span class="blue">Susan:</span>
                                                Vestibulum id ligula porta felis euismod ...
                                            </span>

                                            <span class="msg-time">
                                                <i class="ace-icon fa fa-clock-o"></i>
                                                <span>20 minutes ago</span>
                                            </span>
                                        </span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="clearfix">
                                        <img src="~/Content/Back_End/assets/images/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                                        <span class="msg-body">
                                            <span class="msg-title">
                                                <span class="blue">Bob:</span>
                                                Nullam quis risus eget urna mollis ornare ...
                                            </span>

                                            <span class="msg-time">
                                                <i class="ace-icon fa fa-clock-o"></i>
                                                <span>3:15 pm</span>
                                            </span>
                                        </span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="clearfix">
                                        <img src="~/Content/Back_End/assets/images/avatars/avatar2.png" class="msg-photo" alt="Kate's Avatar" />
                                        <span class="msg-body">
                                            <span class="msg-title">
                                                <span class="blue">Kate:</span>
                                                Ciao sociis natoque eget urna mollis ornare ...
                                            </span>

                                            <span class="msg-time">
                                                <i class="ace-icon fa fa-clock-o"></i>
                                                <span>1:33 pm</span>
                                            </span>
                                        </span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="clearfix">
                                        <img src="~/Content/Back_End/assets/images/avatars/avatar5.png" class="msg-photo" alt="Fred's Avatar" />
                                        <span class="msg-body">
                                            <span class="msg-title">
                                                <span class="blue">Fred:</span>
                                                Vestibulum id penatibus et auctor  ...
                                            </span>

                                            <span class="msg-time">
                                                <i class="ace-icon fa fa-clock-o"></i>
                                                <span>10:09 am</span>
                                            </span>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown-footer">
                            <a href="inbox.html">
                                See all messages
                                <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="purple  dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (Session["IDChucVu"].ToString() != "1")
                            {
                                <img class="nav-user-photo" src="~/HinhAnh/@Session["Anh"].ToString()" style="height:40px;width:45px;" />
                            }
                            <span class="user-info">
                                <small>Chào, </small>
                                <span>@User.Identity.Name</span>
                            </span>
                        }
                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="ace-icon fa fa-cog"></i>
                                Settings
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index","Info")">
                                <i class="ace-icon fa fa-user"></i>
                                Profile
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="@Url.Content("~/Login/Logout")">
                                <i class="ace-icon fa fa-power-off"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>